blog/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('blogs.urls', namespace='blogs')),
    url(r'^users/', include('users.urls', namespace='users')),

]

blogs/urls.py
from django.conf.urls import url

from blogs import views
app_name = '[blogs]'
urlpatterns = [
    url(r'^$',views.index,name='index'),
    url(r'^topics/$',views.topics,name='topics'),
    url(r'^topics/(?P<topic_id>\d+)/$',views.topic,name='topic'),
    url(r'^new_topic/$',views.new_topic,name='new_topic'),
    url(r'^new_entry/(?P<topic_id>\d+)/$',views.new_entry,name='new_entry'),
    url(r'^edit_entry/(?P<entry_id>\d+)/$',views.edit_entry,name='edit_entry'),

]

users/urls.py
from django.conf.urls import url
from django.contrib.auth.views import LoginView

from users import views

app_name = '[users]'
urlpatterns = [
    url(r'^login/$',LoginView.as_view(template_name='login.html'),name='login'),
    url(r'^logout/$',views.logout_view,name='logout'),
    url(r'^register/$',views.register,name='register'),
]

blogs/models.py
from django.contrib.auth.models import User
from django.db import models

class Topic(models.Model):
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)
    owner = models.ForeignKey(User,on_delete=models.CASCADE)
    def __str__(self):
        return self.text


class Entry(models.Model):
    topic = models.ForeignKey(Topic,on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    class Meta:
        verbose_name_plural='entries'

    def __str__(self):
        if len(self.text) >50:
            return self.text[:50]+'...'
        else:
            return self.text

users/models.py
from django.db import models

# Create your models here.

blogs/forms.py
from django import forms

from blogs.models import Topic,Entry


class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}
class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text':''}
        widgets = {'text':forms.Textarea(attrs={'cols':80})}

blogs/views.py
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect, Http404
from django.shortcuts import render

# Create your views here.
from django.urls import reverse

from blogs.forms import TopicForm,EntryForm
from blogs.models import Topic, Entry


def index(request):
    return render(request,'index.html')

@login_required
def topics(request):
    topics = Topic.objects.filter(owner=request.user).order_by('date_added')
    context = {'topics':topics}
    return render(request,'topics.html',context)


def topic(request,topic_id):
    topic = Topic.objects.get(id=topic_id)
    if topic.owner != request.user:
        raise Http404
    entries = topic.entry_set.order_by('-date_added')
    context = {'topic':topic,'entries':entries}

    return render(request,'topic.html',context)

@login_required
def new_topic(request):
    if request.method !='POST':
        form = TopicForm()
    else:
        form = TopicForm(request.POST)
        if form.is_valid():
            new_topic = form.save(commit=False)
            new_topic.owner = request.user
            new_topic.save()
            return HttpResponseRedirect(reverse('blogs:topics'))

    context = {'form':form}
    return render(request,'new_topic.html',context)


def new_entry(request,topic_id):
    topic = Topic.objects.get(id=topic_id)

    if request.method != 'POST':
        form = EntryForm()
    else:
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('blogs:topic',args=[topic_id]))
        else:
            raise Http404
    context = {'topic':topic,'form':form}

    return render(request,'new_entry.html',context)


def edit_entry(request,entry_id):

    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if topic.owner != request.user:
        raise Http404
    if request.method != 'POST':
        form = EntryForm(instance=entry)
    else:
        form = EntryForm(instance=entry,data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('blogs:topic',args=[topic.id]))

    context = {'entry':entry,'topic':topic,'form':form}

    return render(request,'edit_entry.html',context)

users/views.py
from django.contrib.auth import logout, authenticate, login
from django.contrib.auth.forms import UserCreationForm
from django.http import HttpResponseRedirect
from django.shortcuts import render

# Create your views here.
from django.urls import reverse


def logout_view(request):
    logout(request)

    return HttpResponseRedirect(reverse('blogs:index'))


def register(request):
    if request.method != 'POST':
        form = UserCreationForm()
    else:
        form = UserCreationForm(data=request.POST)
        if form.is_valid():
            new_user = form.save()
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('blogs:index'))
    context = {'form': form}
    return render(request, 'register.html', context)

templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <title>Document</title>
</head>
<body>

<nav class="navbar navbar-default navbar-static-top">

    <div class="container">
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed"
                    data-toggle="collapse" data-target="#navbar"
                    aria-expanded="false" aria-controls="navbar"></button>
            <a class='navbar-brand' href="{% url 'blogs:index' %}">Blog</a>
        </div>

        <div id="navbar" class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li><a href="{% url 'blogs:topics' %}">Topics</a></li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                {% if user.is_authenticated %}
                    Hello,{{ user.username }}
                    <a href="{% url 'users:logout' %}">登出</a>
                {% else %}
                    <a href="{% url 'users:login' %}">登录</a>
                    <a href="{% url 'users:register' %}">注册</a>
                {% endif %}
            </ul>
        </div>

    </div>
</nav>


<div class="container">
    <div class="page-header">
        {% block header %}

        {% endblock %}
    </div>
    <div>
        {% block content %}

        {% endblock %}
    </div>
</div>


<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
        integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
        crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
        integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
        crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
        integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
        crossorigin="anonymous"></script>
</body>
</html>

templates/edit_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>edit entry</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
<p><a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a></p>
    <p>编辑内容</p>
    <form action="{% url 'blogs:edit_entry' entry.id %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button name="submit">保存修改</button>
    </form>
{% endblock %}
</body>
</html>

templates/index.html
{% extends 'base.html' %}

{% block header %}
    <div class='jumbotron'>
        <h1>Track your learning.</h1>
    </div>
{% endblock %}

{% block content %}
    <h2>
        <a href="{% url 'users:register' %}">Register an account</a> to make
        your own Learning Log, and list the topics you're learning about.
    </h2>
    <h2>
        Whenever you learn something new about a topic, make an entry
        summarizing what you've learned.
    </h2>
{% endblock %}

templates/login.html
{% extends 'base.html' %}

{% block header %}
    <h2>Log in to your account.</h2>
{% endblock %}

{% block content %}
    <form role="form" method="post" action="{% url 'users:login' %}" class="form">
        {% csrf_token %}

        {{ form.as_p  }}
            <button name="submit" class="btn btn-primary">log in</button>


        <input type="hidden" name="next" value="{% url 'blogs:index' %}"/>
    </form>
{% endblock %}

templates/new_entry.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>new entry</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
    <p><a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a></p>
    <p>添加新内容</p>
    <form action="{% url 'blogs:new_entry' topic.id %}" method="post">

        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">确认添加</button>
    </form>
{% endblock %}
</body>
</html>

templates/new_topic.html
{% extends 'base.html' %}

{% block header %}
<h2>Add a new topic:</h2>
{% endblock header %}


{% block content %}
<form action="{% url 'blogs:new_topic' %}" method='post'
class="form">
{% csrf_token %}
{{ form.as_p }}
<button name="submit" class="btn btn-primary">add topic</button>
{% endblock %}
</form>

templates/register.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>register</title>
</head>
<body>
{% extends 'base.html' %}
{% block content %}
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button name="submit">注册</button>
{#        <input type="hidden" name="next" value="{% url 'blogs:index' %}">#}
    </form>
{% endblock %}
</body>
</html>

templates/topic.html
{% extends 'base.html' %}

{% block header %}
    <h2>{{ topic }}</h2>
{% endblock header %}
{% block content %}
    <p>
        <a href="{% url 'blogs:new_entry' topic.id %}">add new entry</a>
    </p>
    {% for entry in entries %}
        <div class="panel panel-default">
            <div class="panel-heading">
                <h3>
                    {{ entry.date_added|date:'M d, Y H:i' }}
                    <small>
                        <a href="{% url 'blogs:edit_entry' entry.id %}">
                            edit entry</a>
                    </small>
                </h3>
            </div>
            <div class="panel-body">
                {{ entry.text|linebreaks }}
            </div>
        </div> <!-- panel -->
    {% empty %}
        There are no entries for this topic yet.
    {% endfor %}
{% endblock content %}

templates/topics.html
{% extends 'base.html' %}

{% block header %}
<h1>Topics</h1>
{% endblock header %}

{% block content %}

    <ul>
        {% for topic in topics %}

                <li><h3><a href="{% url 'blogs:topic' topic.id %}">{{ topic }}</a></h3></li>

        {% empty %}
            <li>No topics have been added yet.</li>

        {% endfor %}

    </ul>
    <h3><a href="{% url 'blogs:new_topic' %}">添加新主题</a></h3>
{% endblock %}